### ISSUE TITLE
No location to put images in

### ISSUE THREAD

**Issue by codemerlin** [FountainJS/generator-fountain-angular1#62]
https://github.com/Swiip/generator-gulp-angular 

had assets/images ,

when you are not using any module loader and using only bower

**Comment by raptdwar** [comment]
`gulp serve` serve files from both .tmp folder and src folder, simply create the folders you need directly inside the src folder.
when you `gulp build`, those files are copied to dist folder.

**Comment by octavioamu** [comment]
not if is used images in the css, the structure changes and not pointing to the images... also I create a folder with static jsons and not being copied to the dist

**Comment by josx** [comment]
Would be great to have this feature as optional.

**Comment by Swiip** [comment]
Sorry but... We try to keep the generated projects as simple as possible. I don't think creating empty directory to indicate where to put assets is needed. Just put them where you want.

**Comment by octavioamu** [comment]
Having like optional is not having empty folder,  and just putting a folder
with images anywhere is not going to work in production.  I think if the
generator intent to be a general solution for projects,  even small
projects will have images, like css or JS all assets must be considerate in
a multi propose generator.
