### ISSUE TITLE
hello component should render hello world FAILED

### ISSUE THREAD

**Issue by tchicotti** [FountainJS/generator-fountain-angular1#71]
I installed the current version and when I tried `npm run serve`
I got this error on console

```
Error: [$compile:multidir] Multiple directives [app, app] asking for template on: <app class="ng-scope">
```

When I run the 'npm run test' this is what I got on terminal

```
PhantomJS 2.1.1 (Linux 0.0.0): Executed 22 of 29 SUCCESS (0 secs / 0.173PhantomJS 2.1.1 (Linux 0.0.0) hello component should render hello world FAILED
	Error: [$compile:multidir] Multiple directives [app, app] asking for template on: <app class="ng-scope">
```

**Comment by tchicotti** [comment]
I solved the problem removing the ./tmp folder, because I note that error coming from a file inside of it.

**Comment by micaelmbagira** [comment]
Duplicate of https://github.com/FountainJS/generator-fountain-webapp/issues/87
