### ISSUE TITLE
Add Support For CSS

### ISSUE THREAD

**Issue by JimTheMan** [FountainJS/generator-fountain-angular1#72]
HOW is there is no css at all in this project. When I create a new css or scss file webpack completely ignores it. How can I use css in this project??

**Comment by JimTheMan** [comment]
Didn't realize I had to manually add every css mile manually to in index.js...

What happened to the gulp-angular auto-injector?

**Comment by micaelmbagira** [comment]
@JimTheMan  If you use less or scss, you can just use `@import 'myfile.scss'` in `index.scss` and only import this one in `index.js`. If you use bower, then it will be auto injected.
