### ISSUE TITLE
How To Turn Off Linting?

### ISSUE THREAD

**Issue by JimTheMan** [FountainJS/generator-fountain-angular1#73]
Gulp serve doesn't reload the page unless all linting passes. This is outrageous. What's even worse, there is nothing in the webpack gulp task to turn off linting...

**Comment by tbezman** [comment]
Hey guys, for anyone else that had this issue, the way I was able to disable it was by going to the webpack configuration files and removing the loader for eslint.

The webpack config files are in conf/ . I had to change webpack-dist.conf.js webpack-test.conf.js and webpack.conf.js
