### ISSUE TITLE
Problem on 404 techs.json on a new project ( dist/src )

### ISSUE THREAD

**Issue by Chklang** [FountainJS/generator-fountain-angular1#78]
## Description

I've created a new project (angular1, webpack, typescript, css, routeUI, jenkins) and i've tried the command gulp build (or gulp serve:build)

### Error Message & Stack Trace

When i run the dist webapp i've a 404 on techs.json. It try to GET /app/techs/techs.json, but the techs.json is into folder /src/app/techs/techs.json

### Config

Copy the content from `.yo-rc.json`:

```json
{
  "generator-fountain-angular1": {
    "version": "0.7.2",
    "props": {
      "framework": "angular1",
      "modules": "webpack",
      "js": "typescript",
      "ci": [
        "jenkins"
      ],
      "css": "css",
      "resolved": "C:\\Users\\Chklang\\AppData\\Roaming\\npm\\node_modules\\generator-fountain-webapp\\node_modules\\generator-fountain-angular1\\generators\\app\\index.js",
      "namespace": "fountain-angular1",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "sample": "techs",
      "router": "uirouter"
    }
  }
}
```

## Relevant Links

(My project is not yet commited because it's for the initialization)

## Environment

```
Node.js v4.4.6
win32 6.1.7601
yo --version : 1.8.5
npm --version : 
{ npm: '4.0.5',
  ares: '1.10.1-DEV',
  http_parser: '2.5.2',
  icu: '56.1',
  modules: '46',
  node: '4.4.6',
  openssl: '1.0.2h',
  uv: '1.8.0',
  v8: '4.5.103.36',
  zlib: '1.2.8' }
```

I use npm3, and i've done "npm3 install -g yo generator-fountain-webapp" before the creation of the application.

**Comment by micaelmbagira** [comment]
@Chklang Your version is quite old, can you try to update to the last version (rc2) and tell us if it happens again ?

**Comment by Chklang** [comment]
You're rights. I've tried many times npm3 i -g [...] but with "npm i -g[...]" it's works. I must not use npm3 on global in windows...

Thanks!!
