### ISSUE TITLE
Different generated templateUrl between component.js and component.spec.js

### ISSUE THREAD

**Issue by zuhrasofyan** [FountainJS/generator-fountain-angular1#80]
Suppose I generate a component using command `yo fountain-angular1:component --name myComponent --dir components/myComponent`

The result will create:
`templateUrl: 'app/components/myComponent/myComponent.html'` in myComponent.js
but will create 
`templateUrl: 'app/myComponent.html'` in myComponent.spec.js

**Comment by zckrs** [comment]
Maybe fixed by https://github.com/FountainJS/generator-fountain-angular1/pull/76 ?
