### ISSUE TITLE
Bootstrap CSS not injected with gulp serve

### ISSUE THREAD

**Issue by afarazit** [FountainJS/generator-fountain-angular1#85]
Having the same issue as this [one](https://github.com/Swiip/generator-gulp-angular/issues/631) from [Swiip/generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular) repo

When installing bootstrap to 3.3.4 it gets injected, for 3.3.5+ it doesn't.

**Comment by Swiip** [comment]
It's due to a change of Bootstrap which list CSS in its bower.json in the 3.3.4 and remove it after that. Never really know why they done that.

**Comment by fedy2** [comment]
We have the same issue. There is any issue open in Bootstrap project?

**Comment by afarazit** [comment]
@fedy2 I installed 3.3.4 and it knows runs as it should

**Comment by fedy2** [comment]
We solved in the same way, but we want to know if the Boostrap project is trying to solve the issue.
